// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWmFmAsG9wzxtPs_J1NnH296FL-C0A8to',
    appId: '1:179474953075:web:013f881676887ac2618b06',
    messagingSenderId: '179474953075',
    projectId: 'clinic-appoint-app-1cb2c',
    authDomain: 'clinic-appoint-app-1cb2c.firebaseapp.com',
    storageBucket: 'clinic-appoint-app-1cb2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOhtkqgS6jz9mdXbUgQhsDU7fbSd-shJA',
    appId: '1:179474953075:android:ee0f483797d2baaa618b06',
    messagingSenderId: '179474953075',
    projectId: 'clinic-appoint-app-1cb2c',
    storageBucket: 'clinic-appoint-app-1cb2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2NsweKc40hyjd_IL9sgdht-V303swIU',
    appId: '1:179474953075:ios:7da1695cc873e1b1618b06',
    messagingSenderId: '179474953075',
    projectId: 'clinic-appoint-app-1cb2c',
    storageBucket: 'clinic-appoint-app-1cb2c.appspot.com',
    iosClientId: '179474953075-k667u6nsd7fc0fnus2kmr0b5si7ulqie.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2NsweKc40hyjd_IL9sgdht-V303swIU',
    appId: '1:179474953075:ios:3b44338be5586906618b06',
    messagingSenderId: '179474953075',
    projectId: 'clinic-appoint-app-1cb2c',
    storageBucket: 'clinic-appoint-app-1cb2c.appspot.com',
    iosClientId: '179474953075-llk8tvdtjdadq10m66hsvdn9vqn90j2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
